include:
  remote: 'https://raw.githubusercontent.com/ebi-ait/gitlab-ci-templates/master/build-release-deploy.yml'

Unit Test:
  variables:
    INGEST_SCHEME: https
    INGEST_HOST: api.ingest.dev.archive.data.humancellatlas.org
    INGEST_PORT: 443
  image: quay.io/ebi-ait/ingest-base-images:node_carbon
  script:
    - npm install
    - npm run test
