include:
  remote: 'https://raw.githubusercontent.com/ebi-ait/gitlab-ci-templates/master/build-release-deploy.yml'

Unit Test:
  image: quay.io/ebi-ait/ingest-base-images:node_carbon
  script:
    - npm install -g jest
    - npm run test
