include:
  remote: 'https://raw.githubusercontent.com/ebi-ait/gitlab-ci-templates/master/build-release-deploy.yml'

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

Unit Test:
  image: quay.io/ebi-ait/ingest-base-images:node_carbon
  stage: build
  script:
    - npm run test
